# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='img',
            field=models.CharField(default=12, max_length=100, verbose_name='小说封面'),
        ),
    ]
