# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20180828_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name': '小说', 'verbose_name_plural': '小说'},
        ),
        migrations.RemoveField(
            model_name='art',
            name='change_time',
        ),
        migrations.RemoveField(
            model_name='art',
            name='pulish_data',
        ),
    ]
