# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_remove_art_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-pulish_data'], 'verbose_name': '小说', 'verbose_name_plural': '小说'},
        ),
        migrations.AddField(
            model_name='art',
            name='tags',
            field=models.ManyToManyField(default=1, to='art.Tag', verbose_name='标签'),
        ),
    ]
