# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 02:27
from __future__ import unicode_literals

import art.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_auto_20180829_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='章节名称')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('pulish_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '单章详情',
                'verbose_name_plural': '单章详情',
                'db_table': 't_chapter',
                'ordering': ['pulish_time'],
            },
        ),
        migrations.CreateModel(
            name='Rollset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('free_level', models.IntegerField(choices=[(0, '免费'), (1, 'VIP')], default=0, verbose_name='免费级别')),
            ],
            options={
                'verbose_name': '卷集',
                'verbose_name_plural': '卷集',
                'db_table': 't_roll',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='art',
            name='change_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='art',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=art.models.new_file_name, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='art',
            name='pulish_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='art',
            name='tags',
            field=models.ManyToManyField(to='art.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='rollset',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Art', verbose_name='所属小说'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Rollset', verbose_name='所属卷集'),
        ),
    ]
